feat: EXPOSED-89 Support functions in Create Index
JetBrains/Exposed pull request #1788
Opened 2023-07-10 02:39 UTC by bog-walk

Add support for functional indices.

**Problem 1 - Getting Table Info:**
Data class `Index` currently gets `Table` information from user-provided `columns`. If an index is defined using only functions, the `table` property cannot be derived, since `Function` class does not store such info. In this case, table info needs to be directly provided, so this is done automatically if a user defines `functions`.

**Problem 2 - Naming the Index:**
Current behavior is to append column names to table name. `Function` class does not store a name, so it will be derived from the function string (works for Exposed functions of the form NAME(expr)). If a custom function doesn't have this format, the entire string is used instead.
- _Alternative_: Force users to provide a `customIndexName` if functions are included.

**Problem 3 - Multiple Vararg Prohibited:**
All current index creation functions have a parameter named `columns` that only accepts `List<Column<*>>`. Multiple function arguments need to be supported, but a second `vararg` cannot be used, so the new parameter accepts `List<ExpressionWithColumnType<*>>` instead.
- _Alternative_: Change `columns` type to this mutual super class so the user could easily provide column and function arguments together without named arguments. But then the name `columns` would be misleading and would need to be replaced with something like `columnsAndFunctions` or `keyFields`, which would break uses that include named arguments. This would also break Exposed code that uses `Index.columns`, which would require handling/filtering to provide expected  `List<Column<*>>`.

**Note:**
- Add `dropIndex()` override for Oracle as default was not correct.

2023-07-10 02:46 UTC, bog-walk commented on exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt
>      }
The 2 `require()` checks should prevent this `!!` from ever throwing an NPE.

2023-07-10 07:16 UTC, e5l requested changes

2023-07-10 07:16 UTC, e5l commented on exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt
> +    ): Unit =
I wouldn't use `=` with `Unit` return type

2023-07-10 07:16 UTC, e5l commented on exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt
> +    val functions: Pair<Table, List<ExpressionWithColumnType<*>>>? = null
please avoid using Pair in public api

2023-07-12 07:02 UTC, e5l approved these changes

2023-07-12 09:29 UTC, merged