feat: Add migrate function
JetBrains/Exposed pull request #2043
Opened 2024-04-08 11:02 UTC by joc-a

2024-04-09 19:59 UTC, jackgisel-RL reviewed
This looks awesome. We are excited to see this!

2024-04-10 03:15 UTC, bog-walk reviewed
I think the API's good so far, just the comments. Might also be worth adding a test for a failed migration, if it's possible to simulate that and check the logs +/- query the schema history table.

2024-04-10 05:15 UTC, e5l requested changes
Looks good for me! The only concern I have - to move it in a separate module. Let's think how we can do this

2025-02-07 11:34 UTC, joc-a commented
We have decided that Exposed will not be _applying_ database migrations for now, but will be providing database migration scripts that can be used with Flyway and other database migration libraries.

2025-02-07 11:34 UTC, closed without merging