fix: close ResultSet before closing Statement - suppresses "JDBC resources leaked" warning with agroal
JetBrains/Exposed pull request #2247
Opened 2024-09-21 16:33 UTC by ivan-gomes

#### Description

**Summary of the change**: 

Close ResultSet before closing Statement. Motivation is to suppress "JDBC resource leaked" warning when used with agroal.

**Detailed description**:
[Agroal](https://agroal.github.io/docs.html), a popular `javax.sql.DataSource` implementation as used by [Quarkus](https://quarkus.io/) and others, issues a ["leak report"](https://github.com/agroal/agroal/blob/3cde889cd9c90cfed00ba494ebde9689e4837fb9/agroal-pool/src/main/java/io/agroal/pool/ConnectionHandler.java#L112-L114) before automatically closing tracked ResultSets and Statements. If a Statement is closed before related ResultSets are closed it will trigger a leak report - [ref](https://github.com/agroal/agroal/blob/3cde889cd9c90cfed00ba494ebde9689e4837fb9/agroal-pool/src/main/java/io/agroal/pool/wrapper/StatementWrapper.java#L70-L86).

ex.
```
2024-09-21 11:14:47,325 WARN  [io.agr.pool] (executor-thread-1) Datasource '<default>': JDBC resources leaked: 4 ResultSet(s) and 0 Statement(s)
```

This warning occurs on every query with results and can cause developers concern - [ref](https://kotlinlang.slack.com/archives/C0CG7E0A1/p1712756657120689?thread_ts=1712680200.410719&cid=C0CG7E0A1).

The following is a trace of the "leaked" ResultSet being accounted.
```
addLeakedResultSets:804, ConnectionWrapper (io.agroal.pool.wrapper)
closeTrackedResultSets:72, StatementWrapper (io.agroal.pool.wrapper)
close:84, StatementWrapper (io.agroal.pool.wrapper)
close:72, PreparedStatementWrapper (io.agroal.pool.wrapper)
setHasNext:96, AbstractQuery$ResultIterator (org.jetbrains.exposed.sql)
next:111, AbstractQuery$ResultIterator (org.jetbrains.exposed.sql)
next:91, AbstractQuery$ResultIterator (org.jetbrains.exposed.sql)
next:170, IterableExKt$mapLazy$1$iterator$2 (org.jetbrains.exposed.sql)
firstOrNull:279, CollectionsKt___CollectionsKt (kotlin.collections)
findById:95, EntityClass (org.jetbrains.exposed.dao)
findById:57, EntityClass (org.jetbrains.exposed.dao)
...
```

---

#### Type of Change

Please mark the relevant options with an "X":
- [X] Bug fix
- [ ] New feature
- [ ] Documentation update

Updates/remove existing public API methods:
- [ ] Is breaking change

Affected databases:
- [ ] MariaDB
- [ ] Mysql5
- [ ] Mysql8
- [ ] Oracle
- [ ] Postgres
- [ ] SqlServer
- [ ] H2
- [ ] SQLite

#### Checklist

- [ ] Unit tests are in place
- [ ] The build is green (including the Detekt check)
- [X] All public methods affected by my PR has up to date API docs
- [X] Documentation for my change is up to date

---

#### Related Issues

2024-09-22 19:05 UTC, bog-walk requested changes
Thanks very much for going ahead and opening this PR @ivan-gomes !

Please also add the same fix to the 2 other query `ResultIterator`s: [ReturningStatement](https://github.com/JetBrains/Exposed/blob/main/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/ReturningStatement.kt#L48) and [ExplainQuery](https://github.com/JetBrains/Exposed/blob/main/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ExplainQuery.kt#L46).

Normally in an attempt to keep improving coverage, I'd also ask for a test, but I'll have to deal with that in the backlog. Based on my tests (using `AgroalDataSource` from `agroal-pool` with `h2`), the leak warnings only start from version 2.3+, which requires at minimum jdk 11 and we have to keep using jdk 8 atm.

Thanks again and, once the changes above are made, this fix should make it into the upcoming release.

2024-09-22 20:28 UTC, bog-walk commented
@ivan-gomes From my tests, I'm also seeing that insert statements that return auto-generated keys may produce a leak.
Please add `rs?.close()` either after the [while block](https://github.com/JetBrains/Exposed/blob/main/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/InsertStatement.kt#L101) in `InsertStatement.processResults()` or [after](https://github.com/JetBrains/Exposed/blob/main/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/InsertStatement.kt#L202) `processResults()` is called in `executeInternal()`.

2024-09-23 16:25 UTC, ivan-gomes commented
> Thanks very much for going ahead and opening this PR @ivan-gomes !
> 
> Please also add the same fix to the 2 other query `ResultIterator`s: [ReturningStatement](https://github.com/JetBrains/Exposed/blob/main/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/ReturningStatement.kt#L48) and [ExplainQuery](https://github.com/JetBrains/Exposed/blob/main/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ExplainQuery.kt#L46).
> 
> Normally in an attempt to keep improving coverage, I'd also ask for a test, but I'll have to deal with that in the backlog. Based on my tests (using `AgroalDataSource` from `agroal-pool` with `h2`), the leak warnings only start from version 2.3+, which requires at minimum jdk 11 and we have to keep using jdk 8 atm.
> 
> Thanks again and, once the changes above are made, this fix should make it into the upcoming release.

Done, and verified there weren't any other unhandled occurrences of `PreparedStatement.close()` - didn't find any but you probably already knew that. :)

> @ivan-gomes From my tests, I'm also seeing that insert statements that return auto-generated keys may produce a leak. Please add `rs?.close()` either after the [while block](https://github.com/JetBrains/Exposed/blob/main/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/InsertStatement.kt#L101) in `InsertStatement.processResults()` or [after](https://github.com/JetBrains/Exposed/blob/main/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/InsertStatement.kt#L202) `processResults()` is called in `executeInternal()`.

Done, went with the latter so the assignment and cleanup are colocated.

2024-09-23 21:44 UTC, bog-walk approved these changes
Thanks again for the contribution @ivan-gomes !

2024-09-23 21:45 UTC, merged