fix!: EXPOSED-278 Invalid Oracle statement when adding a new column that is used in a primary key
JetBrains/Exposed pull request #2259
Opened 2024-09-26 12:44 UTC by joc-a

#### Description

**Summary of the change**: Provide a concise summary of this PR. Describe the changes made in a single sentence or short paragraph.

**Detailed description**:
- **What**:
DDL for column in Oracle has changed when it is part of a primary key constraint.
- **Why**:
When adding a new column to an existing table in Oracle, if that new column is used in a primary key, then a separate statement is needed for the primary key otherwise there will be a syntax error. Previously, adding the column and the constraint was being done in one statement.
- **How**:
In `createStatement()` in `Column`, a check was added for Oracle to include a separate statement when there is a primary constraint to be added.
---

#### Type of Change

Please mark the relevant options with an "X":
- [ ] Bug fix
- [ ] New feature
- [ ] Documentation update

Updates/remove existing public API methods:
- [ ] Is breaking change

Affected databases:
- [ ] MariaDB
- [ ] Mysql5
- [ ] Mysql8
- [ ] Oracle
- [ ] Postgres
- [ ] SqlServer
- [ ] H2
- [ ] SQLite

#### Checklist

- [ ] Unit tests are in place
- [ ] The build is green (including the Detekt check)
- [ ] All public methods affected by my PR has up to date API docs
- [ ] Documentation for my change is up to date

---

#### Related Issues

2024-09-26 15:40 UTC, bog-walk requested changes
Please add a note about breaking changes to [doc](https://github.com/JetBrains/Exposed/blob/main/documentation-website/Writerside/topics/Breaking-Changes.md#0560) so it's not forgotten later. All links to breaking changes goes to the site version, which won't be synced until the release, so it's ok to update with every relevant PR.

2024-09-26 15:40 UTC, bog-walk commented on exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateTableTests.kt
> +        withTables(excludeSettings = TestDB.ALL_H2, tables = arrayOf(Book)) { testDb ->
Could H2 also be included? I added it to the same branch as Oracle and the test passed.

2024-09-30 10:09 UTC, joc-a commented
> Please add a note about breaking changes to [doc](https://github.com/JetBrains/Exposed/blob/main/documentation-website/Writerside/topics/Breaking-Changes.md#0560) so it's not forgotten later. All links to breaking changes goes to the site version, which won't be synced until the release, so it's ok to update with every relevant PR.

I decided not to mark this as a breaking change after all, because the Oracle DDL I fixed was not working to begin with and was causing a syntax error, so technically, my change is not "breaking" anything.

2024-10-01 00:32 UTC, bog-walk approved these changes

2024-10-01 06:26 UTC, obabichevjb approved these changes

2024-10-01 10:24 UTC, merged